---
title: "Stoke Data"
author: "Miles Tweed"
date: "5/11/2021"
output: pdf_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r, message=FALSE}
require(tidyverse)
proj.dir <- "/Users/julianpalazzo/New College of Florida/Spring Semester 2021/Statistical Inference 2/final_project"
data.dir <- "data/stroke_prediction"

Stroke <- read_csv(file.path(proj.dir, data.dir, "healthcare-dataset-stroke-data.csv"))
Stroke$bmi <- Stroke$bmi %>% as.numeric()
Stroke <- Stroke %>% mutate(bmi2 = ifelse(is.na(bmi), median(bmi, na.rm = TRUE), bmi)) %>% select(-bmi)
head(Stroke)
```



# Expectation 3
```{r}
lm.obj <- lm(bmi2~., Stroke)

# summary(lm.obj)

step(lm.obj, trace = 0)

lm.reduced <- lm(bmi2 ~ age + hypertension + heart_disease + ever_married + 
    work_type + avg_glucose_level + smoking_status + stroke, data = Stroke)

summary(lm.reduced)
```


# Expectation 6
```{r}
glm.obj <- glm(stroke~., Stroke, family='binomial')

summary(glm.obj)

step(glm.obj, trace = 0)

glm.reduced <- glm(stroke ~ age + hypertension + heart_disease + avg_glucose_level, data = Stroke, family = 'binomial')

summary(glm.reduced)
```